[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fork_url = "https://eth-mainnet.g.alchemy.com/v2/ccQX4mrWFgm0QMkSzv0Cd-EKsqgrC2zP"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
